ТЗ10
IrinaGross/java-filmorate pull request #3
Opened 2023-04-11 07:49 UTC by IrinaGross

2023-04-11 07:58 UTC, IrinaGross commented
По-моему в тестировании postman-ом есть ошибки. Первый запрос популярных фильмов без добавления фильму лайка в моем случае возвращает пустую коллекцию. В тесте ожидается 1 фильм

2023-04-11 08:18 UTC, IrinaGross commented
И вот еще из лога

> Film id=2 add Like from user id=1
> DELETE http://localhost:8080/films/2/like/1

2023-04-11 08:54 UTC, IrinaGross commented
Разобралась

2023-04-12 08:11 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь пару рекомендаций

2023-04-12 08:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmLikesStorage.java
> +    public Comparator<? super Film> ratingComparator() {
Компаратор больше относится к бизнес-логике, а не к хранилищу, поэтому лучше перенести его просто в сервис (можно сделать константой)

2023-04-12 08:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
Здесь можно не указывать onConstructor с `@Autowired`, спринг и так инициализирует объект, так как есть только один конструктор и поля final

2023-04-13 08:16 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-04-18 03:04 UTC, merged